kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcprometheuspushgateway
  namespace: csm-powerstore
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: powerstore-xfs

