kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvcprometheusserver
  namespace: csm-powerstore
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: powerstore-xfs

